version: '3.9'
services:
  db:
    container_name: "${POSTGRES_CONTAINER_NAME}"
    image: postgres:15.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

  tests:
    container_name: tests
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy